# Generated by Django 5.2.4 on 2025-08-01 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateTimeField()),
                ('date_retour_effectif', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('retourne', 'Retourné'), ('en_retard', 'En retard'), ('perdu', 'Perdu')], default='actif', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-date_emprunt'],
            },
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('paye', 'Payé'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('adresse_livraison', models.TextField()),
                ('methode_paiement', models.CharField(blank=True, max_length=50)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='livres.livre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-date_commande'],
            },
        ),
    ]
