# Generated by Django 5.2.4 on 2025-08-01 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livregestions', '0001_initial'),
        ('livres', '0001_initial'),
        ('userauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='bibliothecaire_emprunt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprunts_geres', to='userauth.bibliothecaire'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='livres.livre'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to=settings.AUTH_USER_MODEL),
        ),
    ]
