# Generated by Django 5.2.4 on 2025-08-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livregestions', '0002_initial'),
        ('livres', '0002_commenter'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achat',
            options={'verbose_name': 'Achat', 'verbose_name_plural': 'Achats'},
        ),
        migrations.RemoveField(
            model_name='achat',
            name='adresse_livraison',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='date_commande',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='livre',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='quantite',
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('satuts', models.CharField(choices=[('en_cours', 'EN_COURS'), ('Effectué', 'ÉFFECTUÉ'), ('Echoué', 'ÉCHOUÉ')], max_length=50)),
                ('adresse_livraison', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commande', to='userauth.user')),
            ],
        ),
        migrations.AddField(
            model_name='achat',
            name='commande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='livregestions.commande'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buyer', to='userauth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PanierItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('type_action', models.CharField(choices=[('ACHAT', 'Achat'), ('PRET', 'Prêt')])),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livreitem', to='livres.livre')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='livregestions.panier')),
            ],
            options={
                'verbose_name': 'PanierItem',
                'verbose_name_plural': 'PanierItems',
            },
        ),
        migrations.CreateModel(
            name='CommandeItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande', to='livregestions.commande')),
                ('commandeitems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livre_comander', to='livregestions.panieritems')),
            ],
        ),
    ]
