# Generated by Django 5.2.4 on 2025-08-06 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livregestions', '0003_alter_achat_options_remove_achat_adresse_livraison_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='livre',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='livreItems',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='livregestions.panieritems'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='satuts',
            field=models.CharField(choices=[('en_cours', 'EN_COURS'), ('Effectué', 'ÉFFECTUÉ'), ('Echoué', 'ÉCHOUÉ')], default='EN_COURS', max_length=50),
        ),
        migrations.AlterField(
            model_name='commandeitems',
            name='commandeitems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livre_comander', to='livregestions.panier'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
