# Generated by Django 5.2.4 on 2025-08-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livregestions', '0004_remove_emprunt_livre_emprunt_livreitems_and_more'),
        ('livres', '0005_livre_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='livreItems',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='livre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='livres.livre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('retourne', 'Retourné'), ('en_retard', 'En retard'), ('perdu', 'Perdu')], max_length=20),
        ),
    ]
