# Generated by Django 5.2.4 on 2025-08-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livregestions', '0005_remove_emprunt_livreitems_emprunt_livre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='satuts',
            new_name='statuts',
        ),
    ]
