# Generated by Django 5.2.4 on 2025-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livregestions', '0006_rename_satuts_commande_statuts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panieritems',
            name='type_action',
        ),
        migrations.AddField(
            model_name='panieritems',
            name='date_add',
            field=models.DateTimeField(default='2025-08-17'),
            preserve_default=False,
        ),
    ]
