# Generated by Django 5.2.4 on 2025-08-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livregestions', '0007_remove_panieritems_type_action_panieritems_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panieritems',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
