# Generated by Django 5.2.4 on 2025-08-01 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('auteur', models.CharField(max_length=200, verbose_name='Auteur')),
                ('editeur', models.CharField(max_length=200, verbose_name='Éditeur')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('stock_total', models.PositiveIntegerField(default=1, verbose_name='Stock total')),
                ('stock_disponible', models.PositiveIntegerField(default=1, verbose_name='Stock disponible')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat")),
                ('nombre_emprunts', models.PositiveIntegerField(default=0, verbose_name="Nombre d'emprunts")),
                ('nombre_achats', models.PositiveIntegerField(default=0, verbose_name="Nombre d'achats")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('nombre_pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('langue', models.CharField(default='Français', max_length=50, verbose_name='Langue')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres', to='livres.categorie')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['titre'],
            },
        ),
    ]
