# Generated by Django 5.2.4 on 2025-08-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0001_initial'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_comment', models.DateField(auto_now_add=True)),
                ('note', models.DecimalField(blank=True, decimal_places=0, max_digits=2, max_length=2)),
                ('livre', models.ManyToManyField(related_name='livrecommenter', to='livres.livre')),
                ('user', models.ManyToManyField(related_name='usercommenter', to='userauth.user')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
            },
        ),
    ]
