# Generated by Django 5.2.4 on 2025-08-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0002_commenter'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commenter',
            new_name='Commentaire',
        ),
    ]
