# Generated by Django 5.2.4 on 2025-08-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0003_rename_commenter_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='commentaire',
            field=models.TextField(default='livre vraiment super', max_length=1000),
            preserve_default=False,
        ),
    ]
