# Generated by Django 5.2.4 on 2025-08-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0004_commentaire_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='livres/'),
        ),
    ]
