# Generated by Django 5.2.4 on 2025-08-15 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0005_livre_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='livres.categorie'),
        ),
    ]
